name: Build

on:
  pull_request:
  push: 
    branches:
      - main
      - patch-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:          
      - name: Verify the action runs
        run: |
          echo 'It works'
